### ISSUE TITLE
Ideas to promote the project

### ISSUE THREAD

**Issue by pottekkat** [devcshort/stack-inbox#20]
These are some ideas I have to promote this project.

We can share ideas here and grow the community around this project.

Sharing in the following platforms

https://news.ycombinator.com/show:

https://www.reddit.com/

https://www.producthunt.com/

https://dev.to

https://twitter.com/home

**Comment by devcshort** [comment]
It would be neat to have this project with more people helping out to make it as great as possible. Adding new features and what not.

**Comment by pottekkat** [comment]
You can post it in all these platforms. Then you will get more traffic to this repo and possibly new users and contributors.

**Comment by devcshort** [comment]
Thanks @navendu-pottekkat for the help
